name: Deploy Dudi_Tofu11 OpenTofu Workspace
"on":
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    workflow_dispatch:
        inputs:
            apply:
                description: Should apply OpenTofu changes?
                type: boolean
                default: false
jobs:
    deploy:
        name: Deploy OpenTofu Workspace
        runs-on: ubuntu-latest
        permissions:
            contents: read
            id-token: write
        env:
            FIREFLY_ACCESS_KEY: ${{ secrets.FIREFLY_ACCESS_KEY }}
            FIREFLY_SECRET_KEY: ${{ secrets.FIREFLY_SECRET_KEY }}
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Set deployment parameters
              id: set-params
              run: |-
                if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
                  echo "apply=${{ github.event.inputs.apply }}" >> $GITHUB_OUTPUT
                elif [ "${{ github.event_name }}" = "push" ] && [ "${{ github.ref }}" = "refs/heads/main" ]; then
                  echo "apply=true" >> $GITHUB_OUTPUT
                else
                  echo "apply=false" >> $GITHUB_OUTPUT
                fi
            - name: Setup OpenTofu
              uses: opentofu/setup-opentofu@v1
              with:
                tofu_version: 1.7.1
                tofu_wrapper: false
            - name: Initialize OpenTofu
              id: init
              run: tofu init >& init.log
              continue-on-error: true
            - name: OpenTofu Plan
              id: plan
              if: steps.init.outcome == 'success'
              run: tofu plan -json -out=tf.plan > plan_log.jsonl && tofu show -json tf.plan > plan_output.json && tofu show tf.plan > plan_output_raw.log
              continue-on-error: true
            - name: Firefly Post Plan
              uses: gofireflyio/fireflyci@v0.5.21
              with:
                command: post-plan
                context: ""
                init-log-file: init.log
                plan-json-log-file: plan_log.jsonl
                plan-output-file: plan_output.json
                plan-raw-log-file: plan_output_raw.log
                workspace: Dudi_Tofu11
              continue-on-error: true
            - name: OpenTofu Apply
              if: steps.set-params.outputs.apply == 'true' && steps.plan.outcome == 'success'
              run: tofu apply -auto-approve -json > apply_log.jsonl
              continue-on-error: true
            - name: Firefly Post Apply
              if: steps.set-params.outputs.apply == 'true' && steps.plan.outcome == 'success'
              uses: gofireflyio/fireflyci@v0.5.21
              with:
                apply-log-file: apply_log.jsonl
                command: post-apply
                context: ""
                workspace: Dudi_Tofu11
              continue-on-error: true
